<?php

namespace Home\Model\Entry;

use Home\Model\Common\LogUtils;

class InitAction500092 extends InitActionTelecom
{

    protected function getDecodeEPGInfo($infoValue)
    {
        return urldecode($infoValue); // TODO: Change the autogenerated stub
    }

    protected function getInfoByXML($xmlObj)
    {
        $epgInfoMap["userId"] = $xmlObj->userId;
        $epgInfoMap["userToken"] = $xmlObj->userToken;
        $epgInfoMap["GroupId"] = $xmlObj->groupId;
        $epgInfoMap["stbId"] = ($xmlObj->stbId != null && !empty($xmlObj->stbId)) ? $xmlObj->stbId : "";
        $epgInfoMap["userIP"] = $xmlObj->ip;
        $epgInfoMap["userMAC"] = $xmlObj->mac;
        $epgInfoMap["partner"] = $xmlObj->partner;
        $epgInfoMap["serverPath"] = $xmlObj->serverPath;
        $epgInfoMap["returnUrl"] = $xmlObj->returnurl;
        
        LogUtils::info("user epgInfoMap====> " . json_encode($epgInfoMap)); // 把INFO信息写入文档
        return $epgInfoMap;
    }

    public function handleEPGInfoMap($epgInfoMap)
    {
        // 局方大厅返回地址
        MasterManager::setIPTVPortalUrl(urldecode($epgInfoMap["returnUrl"]));
        // 用户账号
        MasterManager::setAccountId($epgInfoMap["userId"]);
        // 终端ID
        MasterManager::setSTBId($epgInfoMap["stbId"]);
        return $epgInfoMap;
    }

}