<?php

namespace Home\Model\Activity;


use Home\Model\Common\LogUtils;
use Home\Model\Common\SessionManager;
use Home\Model\Entry\MasterManager;
use Think\Exception;

class ActivityStaticData
{

    /** 健康测一测（中国联通EPG-山东省独立活动）*/
    const SUB_ID_ACTIVITY_HEALTH_TEST20181210 = "ActivityHealthTest20181210";


    //////////////////////////////////////////////////////////////////////////
    //                        山东健康测一测题库                             //
    // ---------------------------------------------------------------------//
    //////////////////////////////////////////////////////////////////////////


    /**
     * 获取问题子集话题
     *
     * @return mixed
     */
    public static function getSDhealthTopic($index)
    {

        $topics = array(
            array('index' => 0, 'topic' => array("睡眠质量测试题", "自我保健常识自测", "运动观念自测", "疲劳程度自测", "测最适合你的焦虑心理消除法", "用脑习惯测试", "疲劳程度测试", "人体节律自测", "测一测你的身体是不是容易受伤？", "对于转基因食品的认知程度自测", "女性抑郁症程度自测", "肾脏疾病程度自测")),
            array('index' => 1, 'topic' => array("亚健康状态自测", "更年期测试", "大便指数自测", "血管性老年痴呆在家自测表", "自测动脉衰老程度", "高血压征兆测试", "患高血脂征兆自测", "患心脏疾病症状自测", "患脂肪肝征兆自测", "患糖尿病征兆自测", "患肾脏疾病征兆自测", "肝癌程度自测")),
            array('index' => 2, 'topic' => array("你是否是易胖体质", "测你的发胖指数", "你的体质是热还是寒", "可怕暴食症，你有吗？", "你身体里究竟有多少毒？", "测试一下你十年后的体重", "你身体哪个部位最容易胖", "你会尝试哪种减肥方法", "你的减肥动力", "你的减肥压力有多大", "身体酸碱体质自测", "体质自测")),
            array('index' => 3, 'topic' => array("你的肌肤年龄", "测测你的肤质", "你看上去像25岁吗", "肌肤中毒有多深", "你会给肌肤正确保湿吗？", "你是否需要补血？", "你是不是敏感皮肤", "你是防晒高手吗", "你的美容IQ有多高", "从头发测出亚健康", "肌肤敏感程度测定", "看看你的头发是否受损")),
            array('index' => 4, 'topic' => array("你的饮食是否合理", "你所缺的营养是什么", "你的饮食是否健康", "你的饮食习惯值多少分，厨房健康指数自测", "脂肪摄入量自测", "盐的摄入量自测", "维生素常识自测", "锌指标自测", "铁指标自测", "饮食营养常识自测", "饮食卫生指数自测")),
            array('index' => 5, 'topic' => array("血管老化程度自测", "忧郁指数自测", "女性更年期指数自测", "患老年痴呆征兆自测", "男性更年期指数自测", "急迫性指数测验", "身体发冷究竟是什么原因？", "结肠炎、结肠息肉程度自测", "高尿酸血症程度自测", "你便秘吗", "脂肪肝程度自测", "动脉粥样硬化程度自测")),

        );
        $topic = $topics[$index];
        try {
            MasterManager::setAnswerInfo($topic);
        } catch (Exception $e) {
            LogUtils::error("ActivityConstant::getSDAnswer()  ---->>> exception: " . $e->getMessage());
        }
        return $topic;
    }

    /**
     * 从数组题库中获取对应话题的题目
     *
     * @return mixed
     */
    public static function getSDAnswer($homeIndex, $answersType)
    {
        $answers = array(
            /*
             * 健康测试
             * */
            array(
                array(array('title' => '睡眠时间很不规律，不能按时上床睡觉：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '工作或娱乐至深夜：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '躺在床上，脑子里浮现的全是白天见过的人和发生的事，难以入睡：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '入睡后稍有动静就能察觉：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '整夜做梦，醒来时觉得很累：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '很早就醒来，而且再也睡不着了：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '稍有不顺心的事就彻夜难眠：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '换个环境就难以入睡：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '一上夜班就睡眠不好：', 'answerList' => array('经常', '有时', '很少', '从未',)), array('title' => '使用安眠药才能安然入睡：', 'answerList' => array('经常', '有时', '很少', '从未'))),
                array(array('title' => '您认为下列哪个症状不必求医？', 'answerList' => array('A.疲劳不堪', 'B.慢性消化不良', 'C.冬季流感')), array('title' => '夏天如果外出有中暑症状，应立即', 'answerList' => array('A.尽快到凉快的地方休息', 'B.立即返回家中', 'C.坚持前行，尽快赶到目的地')), array('title' => '您通常多长时间换一次牙刷?', 'answerList' => array('A.半年', 'B.三个月', 'C.等到牙刷不能用了')), array('title' => '您认为下列哪一种方法预防感冒或流感最无效?', 'answerList' => array('A.天冷时不出门，呆在家里', 'B.经常洗手', 'C.注射抗流感针药')), array('title' => '如果您有冻疮，可以采取下列那种办法？', 'answerList' => array('A.用火烘烤冻疮部位', 'B.用热水擦洗冻疮部位', 'C.用冷水或雪擦洗冻疮部位')), array('title' => '使用计算机或阅读时，您会隔多久让眼睛休息一下?', 'answerList' => array('A.半小时', 'B.一小时', 'C.眼睛累了就休息')), array('title' => '您同意下列哪种说法?', 'answerList' => array('A.即使乌云密布，皮肤也有晒伤的可能', 'B.不想晒黑皮肤，应用防晒系数在10以下的防晒油', 'C.肤色较深的人无须用防晒油')), array('title' => '您觉得哪种呼吸方式更健康?', 'answerList' => array('A.用鼻子呼吸', 'B.用嘴呼吸', 'C.上述两种方法差不多')), array('title' => '如果您想减肥，您会选择哪种方法?', 'answerList' => array('A.不吃含淀粉食物', 'B.节食', 'C.减少喝酒')), array('title' => '您觉得哪种方法对头发的损伤最小?', 'answerList' => array('A.染发', 'B.用吹风机吹发', 'C.烫发'))),
                array(array('title' => '运动能增强大脑功能。', 'answerList' => array('A.√', 'B.×')), array('title' => '运动量越大越有利于身体健康。', 'answerList' => array('A.√', 'B.×')), array('title' => '冬天参加体育锻炼会得关节炎。', 'answerList' => array('A.√', 'B.×')), array('title' => '早晨空腹锻炼有害健康。', 'answerList' => array('A.√', 'B.×')), array('title' => '大雾天气时不宜在室外运动。', 'answerList' => array('A.√', 'B.×')), array('title' => '腰身减肥的最好办法是做腹部运动。', 'answerList' => array('A.√', 'B.×')), array('title' => '为了保持适当的健康水平，你只需要一星期运动两次。', 'answerList' => array('A.√', 'B.×')), array('title' => '为了减肥，当运动时你应该尽量出一身汗。', 'answerList' => array('A.√', 'B.×')), array('title' => '慢跑一公里比步行一公里要消耗更多的热量。', 'answerList' => array('A.√', 'B.×')), array('title' => '锻炼后数分钟内，如果你的呼吸不能恢复正常，可能你的运动量太大。', 'answerList' => array('A.√', 'B.×')), array('title' => '散步时伸展运动使肌肉保持灵活。', 'answerList' => array('A.√', 'B.×')), array('title' => '一天中你最少应有20分钟进行锻炼。', 'answerList' => array('A.√', 'B.×'))),
                array(array('title' => '在处理一些重要或是紧急的公务中，我经常掌心冰冷或出汗：', 'answerList' => array('A.常常如此', 'B.右时如此', 'C.极少如此')), array('title' => '晚上没有什么特别的事时，我也会拖到很晚才睡：', 'answerList' => array('A.从不如此', 'B.有时如此', 'C.常常如此')), array('title' => '当同事的意见和我发生冲突时，我：', 'answerList' => array('A.感到恼火，甚至有时愤怒', 'B.介于A、C之间', 'c.冷静考虑对方的观点和立场')), array('title' => '当被通知领导找我时，我总会一下子紧张起来：', 'answerList' => array('A.是的', 'B.不一定', 'C.不是的')), array('title' => '办事拖延，我似乎也不太但;由此产生的后果：', 'answerList' => array('A.是的', 'B.介于A、C之间', 'c.不是的')), array('title' => '最近我发现我对于以前喜欢纳娱乐活动其实并不太感兴趣：', 'answerList' => array('A.是的', 'B.说不准', 'c.不是的')), array('title' => '在下班时间接到显不公司号码的来电时，要很久才接听或者干脆不接：', 'answerList' => array('A.是的', 'B.有时如此', 'c.从不如此')), array('title' => '我被不是很熟的人认为干得不错，我也竭力保持别人这种对我的印象：', 'answerList' => array('A.我总是如此', 'B.介于A、C之间', 'c.几乎没有这种想法')), array('title' => '在休息日总是旨昏沉沉睡到下午，然后担心时间过得太快：', 'answerList' => array('A.是的', 'B.介于A、c之间', 'c.不是的')), array('title' => '计划表开始变得不重要，我不再往上填写各种安排了：', 'answerList' => array('A.是的', 'B.偶尔也写', 'c.不是的'))),
                array(array('title' => '上班（上学）的你需要搭乘公交车，但总是人满为患，虽然每天都免不了乘坐，但你还是难以适应。为了避开满满的车厢，你会选择什么样的方式呢？', 'answerList' => array('A、提前一个小时起床以避免上班高峰期    ', 'B、自己开车或骑自行车', 'C、即使迟到也要错开高峰时间', 'D、和朋友（同事）一起乘坐来减少一个人挤车的不快'))),
                array(array('title' => '1.对于化妆和发型，你会：', 'answerList' => array('A．尝试各种造型', 'B．有时会试着改变', 'C．几乎从不改变')), array('title' => '2.如果急需决断的时候，你会：', 'answerList' => array('A．凭直觉决定', 'B．小事当机立断，大事认真思考', 'C．左思右想，难以决断')), array('title' => '3.正在制定旅行计划，你会：', 'answerList' => array('A．渴望冒险，不怕危险', 'B．一般不会冒险，但也会根据周围的意见，做适当改变', 'C．经过了曾经的失败，要慎重制定计划')), array('title' => '4.阅读传记文学时，你会：', 'answerList' => array('A．“写得都是真的吗？”心存疑问', 'B．都能接受书中的内容，偶尔有疑问', 'C．不抱任何猜疑')), array('title' => '5.有一位被别人提醒要注意的人物，你会：', 'answerList' => array('A．没有先入为主的观念，接触后，再判断', 'B．稍有戒备之心', 'C．表面正常，内心却非常戒备')), array('title' => '6.查阅说明书时，你会：', 'answerList' => array('A．只看必要的地方', 'B．从头到尾通读一遍', 'C．从第一页开始仔细阅读')), array('title' => '7.看电影时，你会：', 'answerList' => array('A．坐右边', 'B．坐左边')), array('title' => '8.学生时代，你擅长：', 'answerList' => array('A．几何', 'B．代数', '')), array('title' => '9.看展览时，你会：', 'answerList' => array('A．依照喜好，喜欢的才看', 'B．依次看')), array('title' => '10.从事于热衷的活动时，你会忘记工作吗？', 'answerList' => array('A．是', 'B．否')), array('title' => '', 'answerList' => array('', '', ''))),
                // 该条测试没有结果陈述--
                array(array('title' => '你有过被疲劳困扰的经历吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你是否需要更多的休息?', 'answerList' => array('A.是', 'B.否')), array('title' => '你感觉到犯困或昏昏欲睡吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你在着手做事情时是否感到费力?', 'answerList' => array('A.是', 'B.否')), array('title' => '你着手做事时不感到费力，但当你继续进行时感到力不从心?', 'answerList' => array('A.是', 'B.否')), array('title' => '你感觉到体力不够吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你感觉到你的肌肉力量比以前减小了吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你感觉到虚弱吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你集中注意力有困难吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你思考时头脑像往常一样清晰、敏捷吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你在讲话时出现口头不利落吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '讲话时，你觉得找到一个合适的字眼很困难吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你现在的记忆力像往常一样吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '你还喜欢做过去习惯做的事情吗?', 'answerList' => array('A.是', 'B.否')), array('title' => '', 'answerList' => array('', '', ''))),
                array(array('title' => '1.皮肤光润，不感到浑身酸痛。', 'answerList' => array('A.是', 'B.否')), array('title' => '2.手指灵活有力，转动自如。', 'answerList' => array('A.是', 'B.否')), array('title' => '3.食欲很好，体重无重大变化。', 'answerList' => array('A.是', 'B.否')), array('title' => '4.早晨醒来头脑清醒，心情舒畅。', 'answerList' => array('A.是', 'B.否')), array('title' => '5.感到自己身体轻捷，步履矫健。', 'answerList' => array('A.是', 'B.否')), array('title' => '6.呼吸非常轻松、顺畅，富有节奏。', 'answerList' => array('A.是', 'B.否')), array('title' => '7.迅速登梯时不大会气喘吁吁。', 'answerList' => array('A.是', 'B.否')), array('title' => '8.无论做什么都集中注意力。', 'answerList' => array('A.是', 'B.否')), array('title' => '9.在工作中从容，不焦躁。', 'answerList' => array('A.是', 'B.否')), array('title' => '10.工作时能专心致志。', 'answerList' => array('A.是', 'B.否')), array('title' => '11.能迅速解决问题而不感到棘手。', 'answerList' => array('A.是', 'B.否')), array('title' => '12.尽管整体工作，也不怎么感到疲劳。', 'answerList' => array('A.是', 'B.否')), array('title' => '13.发生不愉快事情时，从不怒气冲冲。', 'answerList' => array('A.是', 'B.否')), array('title' => '14.晚上能迅速入睡。', 'answerList' => array('', '', ''))),
                // 该条评分规则很复杂---
                array(array('title' => '1.你是否在过去半年内才开始跑步(或中断了一长段时间恢复跑步)？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '2.你每周跑量超过48公里吗？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '3.你每周跑步几天？', 'answerList' => array('A.7天。', 'B.1—2天。', '　C.3—6天。')), array('title' => '4.你每周是否最少有两次力量训练？', 'answerList' => array('A.是的', 'B.不时。')), array('title' => '5.你一年跑几次马拉松比赛？ (注意：那些为了趣味的慢速跑不计算在内)', 'answerList' => array('　A.3次或3次以上。', 'B.2次或2次以下。')), array('title' => '6.过去一年内，你有没有因为伤病而减少跑量或者接受治疗？', 'answerList' => array('A.是的。', '　B.不是。')), array('title' => '7.你步幅过大吗？', 'answerList' => array('A.你的脚落在这条直线前一大段距离处。', 'B.你的脚几乎落在这条直线上。')), array('title' => '8.你的臀大肌力量不够？面对一面镜子，站在一个20厘米高的台阶上。单腿跳下台阶，脚后跟轻轻着地，接着恢复站立姿势，在这个过程中观察自己的动作。每条腿重复三次。', 'answerList' => array('　A.你的盆骨下倾。', '　B.你的膝盖弯曲。', 'C.标准的姿势。')), array('title' => '9.你最近是否经历过生活中一次非常糟糕的变故？你现在是否正处在工作或者生活中一段艰难的时光？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '10.你每晚的睡眠时间是否少于7小时？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '11.你最近是否换了一款新跑鞋？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '　　12.你是否树立了很“高大上”的跑步成绩目标？并且不愿意去调整目标？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '　　13.你是女性跑者吗？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '　　14.你是否6个月都没有来月经？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '　　15.你跑步的时候会遗尿吗？', 'answerList' => array('A.是的。', 'B.不是。')), array('title' => '', 'answerList' => array('', '', ''))),
                array(array('title' => '您是否认为，谷氨酸的过度摄取无害？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不认为，转基因食品有危险？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，转换氨基酸碱基的食品没有问题？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，基因重组不会成为引起大脑发育障碍的诱因？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，转基因食品添加剂不可怕？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，突然变异不一定会冒险？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，如果品种得到改良，利用转基因也是可以的？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，即使是转基因食品或者二次食品也没有问题？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，氨基酸对于孕妇是十分重要的，应该大量摄取？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您不知道这是从几十年前开始实行的？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，只要不改变味道，遗传技术的食品没有问题？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，快餐里没有转基因食品？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，只要不是长期食用就没有问题？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，考虑将来粮食不足，不得不这样？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，今后应该大量发展转基因食品？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，对动物进行遗传基因试验没有问题？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，考虑食物生成线，转基因是个好方法？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，转基因食品作为动物的饲料没有问题？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，即使生产一些自然界不存在的食物也没有关系？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否认为，对于遗传基因技术应该继续研究？', 'answerList' => array('', '', ''))),
                array(array('title' => '1.您对于男性主导的工作感到疲惫吗？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '2.您在办公室遇到性骚扰？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '3.您感觉做家务是一件很痛苦的事情？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '4.您是否经常失眠，醒来后再也睡不着？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '5.您是否不吃早饭，食欲下降？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '6.您是否每天叹息的次数增加？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '7.您是否对小孩的嬉闹声感到厌烦？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '8.您是否感到健忘？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '9.您是否手脚冰凉？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '10.您是否感觉培育孩子的压力大?', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '12.您是否月经不调或者痛经？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '13.您是否经常注意周围人的传言?', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '14.您是否便秘？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '15.您是否经常有小错误或者失败？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '16.您是否认为自己是更年期障碍？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '17.您是否有时候认为死是一件比较快乐的事情？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '18.您是否有妇科病？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '19.您是否不能同时做两件事？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '20.您是否经常接受心理治疗？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
                array(array('title' => '1.您是否最近容易疲劳？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '2.您是否尿液颜色深？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '3.您是否排尿次数减少？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '4.您的尿液中泡沫不易消？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '5.您是否下肢水肿？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '6.您是否有高血压？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '7.您是否多有睡眠不足？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '8.您是否日常生活不规律？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '9.您是否不限制盐分的摄入？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '10.您是否夜间常多次排尿？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '11.您是否在外就餐多?', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '12.您是否是过敏性体质？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '13.您是否反复患膀胱炎？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '14.您是否有排尿等待？（排尿开始困难）', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '15.您是否总胆固醇增高？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '16.您是否出现午后热？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '17.您的直系亲属中是否有肾病患者？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '18.您是否被诊断为糖尿病？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '19.您是否既往有肾结石、尿路结石？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '20.您是否既往有肾炎病史？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
            ),
            /*
             * 疾病测试
             * */
            array(
                array(array('title' => '1．昨天想好的事，今天怎么也记不起来了，而且近一段时间经常出现这种情况。', 'answerList' => array('A.是这样的', 'B.不是')), array('title' => '2．早上起床时，常有头发掉落。', 'answerList' => array('A.是这样的', 'B.不是')), array('title' => '3．经常感到情绪有些抑郁，会对着窗外发呆。', 'answerList' => array('A.有时会这样', 'B.从来不会这样')), array('title' => '4．不想面对同事和上司，有患自闭症趋势。', 'answerList' => array('A.有时会这样', 'B.从来不会这样')), array('title' => '5．害怕走进办公室，觉得工作令人厌烦。', 'answerList' => array('A.有时会这样', 'B.从来不会这样')), array('title' => '6．工作效率下降，上司已对自己不满。', 'answerList' => array('A.经常会这样', 'B.不是')), array('title' => '7．工作1小时就会身体倦怠，胸闷气短。', 'answerList' => array('A.经常会这样', 'B.从来不会')), array('title' => '8．工作情绪无法高涨，最令人不解的是总有莫名其妙的火气，但又没有精力发泄。', 'answerList' => array('A.经常会这样', 'B.从来不会')), array('title' => '9．盼望早早地逃离办公室，为的是能够回家，躺在床上休息片刻。', 'answerList' => array('A.时常这样想', 'B.从没这么想')), array('title' => '三餐进食很少，但与天气因素无关。即使口味非常适合自己，近来饮食也经常味同嚼蜡。', 'answerList' => array('A.是这样的', 'B.不是')), array('title' => '11．对城市污染、噪音非常敏感，比常人更渴望宁静清澈的山水，以便休息身心。', 'answerList' => array('A.时常这样想', 'B.从没这么想')), array('title' => '12．夜里常常失眠，即使睡着了，也老是在做梦的状态中，睡眠质量很糟糕。', 'answerList' => array('A.经常会这样', 'B.不是')), array('title' => '13．不再像以前那样热衷于朋友聚会，有种强打精神、勉强应酬的感觉。', 'answerList' => array('A.经常会这样', 'B.不是')), array('title' => '14．体重有明显下降的趋势，早上起来会发现眼眶深陷、下巴突出。', 'answerList' => array('A.是的', 'B.不是')), array('title' => '15．感觉免疫力在下降，春、秋季流感一来，自己首当其冲，难逃“流运”。', 'answerList' => array('A.是的', 'B.不是')), array('title' => '16．性能力下降，妻子（或丈夫）对自己明显地表示了性要求，但却经常感到疲惫不堪，没有什么欲望。妻子（或丈夫）甚至怀疑自己有外遇了。', 'answerList' => array(' A.是的', 'B.不是'))),
                // 该条没有结果陈述
                array(array('title' => '1.您是否潮热出汗?', 'answerList' => array('A.无', 'B.＜3次/天', 'C.3-9次/天', 'D.≥10次/天')), array('title' => '2.您是否感到异常？', 'answerList' => array('A.无', 'B.有时', 'C.经常有刺痛、麻木、耳鸣等', 'D.经常而且严重')), array('title' => '3.您是否失眠？', 'answerList' => array('A.无 ', 'B.有时', 'C.经常', 'D.经常而且严重，需服药')), array('title' => '4.您是否感到焦躁？', 'answerList' => array('A.无', 'B.有时', 'C.经常，能自控', 'D.经常，不能自控')), array('title' => '5.您是否忧郁？', 'answerList' => array('A.无', 'B.有时', 'C.经常，能自控', 'D.失去生活信心')), array('title' => '6.您是否感到头晕？', 'answerList' => array('A．无', 'B．经常，不影响生活', 'C．影响生活与工作')), array('title' => '8.您是否疲倦无力？', 'answerList' => array('A.无', 'B.有时', 'C.经常', 'D.日常生活受限')), array('title' => '9.您是否肌肉和骨关节痛？', 'answerList' => array('A.无', 'B.有时', 'C.经常，不影响功能', 'D.功能障碍')), array('title' => '10.您是否头痛？', 'answerList' => array('A.无', 'B.有时', 'C.经常，能忍受', 'D.需服药')), array('title' => '11.您是否心悸？', 'answerList' => array('A.无', 'B.有时', 'C.经常，不影响工作', 'D.需治疗')), array('title' => '12.您是否有皮肤蚁走感？', 'answerList' => array('A.无', 'B.有时', 'C.经常，能忍受', 'D.需治疗')), array('title' => '13.您的性生活如何？', 'answerList' => array('A.无', 'B.性欲低下', 'C.性生活困难', 'D.性欲丧失')), array('title' => '14.您是否泌尿系统感染？', 'answerList' => array('A.无', 'B.偶尔', 'C.≤3次/年，能自愈', 'D.＞3次/年，需服药'))),
                // 该条选项太多
                array(array('title' => '1.感到排便费力或困难吗？', 'answerList' => array('不费力', '有时费力', '感到费力', '感到非常困难')), array('title' => '2.每天或每周排便几次？', 'answerList' => array('每天一次或一次以上', '1-2天排便一次', '3-4天排便一次	', '5-6天排便一次', '每周排便一次', '每周少于一次')), array('title' => '3.排便后是否经常有大便未排净的感觉？', 'answerList' => array('很少或没有这种感觉', '有是有', '经常有', '一直有')), array('title' => '4.排便时感到疼痛吗？', 'answerList' => array('有时偶尔疼痛', '有时会感到疼痛', '经常感到疼痛', '几乎一直有疼痛感	'))),
                // 该条没有选项
                array(array('title' => '1.今天是几月几日、星期几？', 'answerList' => array('null', '', '')), array('title' => '2. 早餐(或晚餐)吃了哪些菜？', 'answerList' => array('null', '', '')), array('title' => '3. 请念出下面五个数字：5 - 1 - 4 - 3 - 2，然后再倒回去念一遍。', 'answerList' => array('null', '', '')), array('title' => '4. 100减8等于多少？再减6呢？', 'answerList' => array('null', '', '')), array('title' => '5. 请复述下面三句词组：红玫瑰、白兔子和黑乌鸦。再倒回去念一遍。', 'answerList' => array('null', '', '')), array('title' => '6. 摆出五种物品，先给他看，记好后，再收起来，请对方说出物品名称。', 'answerList' => array('null', '', '')), array('title' => '7. 拿出下列五张卡片：○、△、×、□、十，让他记起来后，再写写看。', 'answerList' => array('null', '', '')), array('title' => '8. 先闲聊2~3分钟后，再问刚才三个词组：红玫瑰、白兔子、黑乌鸦，让他复述一次。', 'answerList' => array('null', '', '')), array('title' => '9. 再问一遍刚才摆出来的5种物品是什幺？', 'answerList' => array('null', '', '')), array('title' => '10. 五张卡片上的记号请他再写一次。', 'answerList' => array('null', '', ''))),
                array(array('title' => '1.长期精神压力大，紧张，失眠。', 'answerList' => array('A.是', 'B.否')), array('title' => '3.爱吃甜食，口重（菜里盐多）。', 'answerList' => array('A.是', 'B.否')), array('title' => '4.偏爱肉类，和油炸食品。', 'answerList' => array('A.是', 'B.否')), array('title' => '5.每天活动时间少于30分钟。', 'answerList' => array('A.是', 'B.否')), array('title' => '6.每天吸烟支数乘以年龄超过400。', 'answerList' => array('A.是', 'B.否')), array('title' => '7.上楼爬楼梯时感到胸痛、胸闷或气急。', 'answerList' => array('A.是', 'B.否')), array('title' => '8.手足发凉、腿脚麻木，有时疼痛。', 'answerList' => array('A.是', 'B.否')), array('title' => '9.有高血压。', 'answerList' => array('A.是', 'B.否')), array('title' => '10.有糖尿病。', 'answerList' => array('A.是', 'B.否')), array('title' => '11.有高脂血症。', 'answerList' => array('A.是', 'B.否')), array('title' => '12.近亲中有人死于心脑血管疾病。', 'answerList' => array('A.是', 'B.否', ''))),
                // 该条评测过于复杂
                array(array('title' => '1.您的体重是否超过标准？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '2.您是否日常生活不规律？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '3.您是否偶有头痛、肩痛？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '4.您是否视物不清？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '5.您是否记忆力下降？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '6.您是否年龄在40岁以上？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '7.您是否吸烟？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '8.您是否几乎每日饮酒？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '9.您的父母、兄弟是否患有高血压？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '10.您上下楼梯是否气短乏力？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '11.您是否应酬频繁？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '12.您是否易疲劳，难以解脱？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '13.你是否下肢静脉曲张？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '14.您是否胆固醇和甘油三酯增高？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '15.您是否经常依赖安眠药入睡？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '16.您是否几乎不运动?', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '17.您是否检查出蛋白尿或血尿？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '18.您是否服用心脏病药物？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '19.您是否常有精神压力？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '20.您是否盐的摄入量大？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
                array(array('title' => '您是否总胆固醇值大于250毫克/毫升？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否甘油三酯值大于250毫克/毫升？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否高密度脂蛋白胆固醇低于50毫克/毫升？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否高密度脂蛋白胆固醇大于150毫克/毫升？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否有糖尿病或者处于高血糖临界状态？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否血尿酸值高？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '鱼类和肉类相比较，您是否更喜欢吃肉类？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不喜欢吃生蔬菜？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不喜欢吃葱、洋葱？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不太爱吃水果？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否吸烟？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否每天晚餐都要喝酒？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您吃面包是否要抹黄油和奶酪？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不太爱运动？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否经常出汗？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否尿液颜色比较深？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否属于肥胖体态？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否很喜欢吃鱼子？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不太爱喝水？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否对外界刺激比较敏感？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
                array(array('title' => '您是否爬楼时觉得气短？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否常常能感觉到自己的心跳？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您夜间是否因呼吸困难而被憋醒？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否常因失眠而服用安眠药？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否吸烟？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否年龄在40岁以上？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否明显超过标准体重？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否日常生活不规律？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您的心电图是否提示心肌缺血或心律不齐？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有盗汗？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您受寒冷刺激时心脏是否难受？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常不吃早餐？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否不注意饮食咸淡？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否患有高血脂？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否患糖尿病或处于高血糖临界状态？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有过胸闷似压重物的感觉？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否会在睡眠中打鼾？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否偶有下肢和足趾酸痛？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否很少运动？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否常感觉烦恼、不安？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否'))),
                array(array('title' => '您是否GPT（谷丙转氨酶）增高？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您的起声波检查是否被诊断为脂肪肝？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否肝功能异常？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否在疲劳后不易恢复？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否对外界刺激敏感？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常饮酒？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否在饮酒的同时会吃干酪或干果？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常吸烟？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您的化验是否提示患高血脂？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否超过标准体重？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否不经常运动？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否皮肤容易感染且不易治愈？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否患糖尿病或者处于高血糖临界状态？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否手掌发红？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否常睡眠不足？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否事务繁忙，长时间未体检？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否较鱼类相比，更喜欢吃肉类食物？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否喜欢重口味的食物？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常在晚上9点以后进晚餐？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常吃夜宵？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否'))),
                array(array('title' => '您是否口渴，多饮现象明显？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否每日都饮酒？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否皮肤容易感染？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有手足末端麻木？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否白天容易疲劳，易有睡意？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否视力急剧下降？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有肥胖倾向？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您的直系亲属中是否有糖尿病患者？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否健忘？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否易犯牙周炎？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否脱发严重？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否疲劳不易解除？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否易伤风感冒？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否睡眠时间短？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有时会出现膀胱炎？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否性欲减退？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否检查出空腹血糖高？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否尿液不太透明，尿中总能见白沫？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否可闻及尿味酸臭？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否已过40岁？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否'))),
                array(array('title' => '您是否最近容易疲劳？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否尿液颜色深？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否排尿次数减少？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否尿中泡沫不易消退？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否下肢水肿？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有高血压？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常睡眠不足？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否日常生活不规律？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否不限制盐分的摄入？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否夜间常多次排尿？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否在外就餐次数多？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否是过敏性体质？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否会排尿等待（排尿开始困难）？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否总胆固醇增高？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否会出现午后发热？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您的直系亲属中是否有肾病患者？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否被诊断为糖尿病？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否既往有肾结石、尿路结石？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有肾炎病史？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否'))),
                array(array('title' => '您是否最近容易疲劳？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否颜面部，手脚浮肿？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否胸背部有血管肿？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否掌心赤红？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否全身乏力？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否患有丙型肝炎？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否有过肝功能异常？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否患过脂肪肝？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您的超声检查是否怀疑肝脏肿瘤？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否肿瘤标志物AFP含量增高？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否对外界刺激敏感？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否患过内痔？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否每天吸烟20支以上？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否每天饮酒？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否经常睡眠不足？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否三餐不规律？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否不吃绿色蔬菜？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否维生素摄入不足？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否牙龈出血？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否')), array('title' => '您是否体重急剧下降？', 'answerList' => array('A.	是', 'B.	不一定', 'C.	否'))),
            ),
            /*
             * 减肥测试
             * */
            array(
                array(array('title' => '常常感到口千舌燥。', 'answerList' => array('A.√ ', 'B.×')), array('title' => '尿液少而且颇色偏黄二', 'answerList' => array('A.√ ', 'B.×')), array('title' => '经常有使秘的现象，粪便又干又硬。', 'answerList' => array('A.√ ', 'B.×')), array('title' => '非常怕热，身体的温度偏高。', 'answerList' => array('A.√ ', 'B.×')), array('title' => '腰部和四肢常有水肿的现象。', 'answerList' => array('A.√ ', 'B.×')), array('title' => '喜欢喝冷饮。', 'answerList' => array('A.√ ', 'B.×')), array('title' => '脸色发红，或是常常面红耳赤。', 'answerList' => array('A.√ ', 'B.×')), array('title' => '肌肉结实肥厚。', 'answerList' => array('A.√ ', 'B.×'))),
                array(array('title' => '现在比18岁时重了5公斤以上？', 'answerList' => array('A.是 ', ' B.否')), array('title' => '吃饭快，一下扫光餐盘中所有东西？', 'answerList' => array('A.是 ', ' B.否')), array('title' => '体重没变．但肌肉却越来越松弛了？', 'answerList' => array('A.是 ', ' B.否')), array('title' => '嘴总吃个不停．包里总能找到零食？', 'answerList' => array('A.是 ', ' B.否')), array('title' => '爱吃油炸食物？', 'answerList' => array('A.是 ', ' B.否')), array('title' => '腰围除以臀围的比例大于0.76？　　', 'answerList' => array('A.是 ', ' B.否')), array('title' => '即使从一楼到二楼，也得搭电梯？', 'answerList' => array('A.是 ', ' B.否')), array('title' => '你总是不断地减肥，又不断地反弹？', 'answerList' => array('', '', ''))),
                array(array('title' => '即使是冬天也喜欢喝冷饮。', 'answerList' => array('A.是', ' B.否')), array('title' => '舌苔呈深红色。', 'answerList' => array('A.是', ' B.否')), array('title' => '说话很快，发音清楚、准确。', 'answerList' => array('A.是', ' B.否')), array('title' => '唾液分泌旺盛。', 'answerList' => array('A.是', ' B.否')), array('title' => '手心长时间保持热暖状态。', 'answerList' => array('A.是', ' B.否')), array('title' => '两颊颜色红润。', 'answerList' => array('A.是', ' B.否')), array('title' => '经常不自觉地睁大眼睛。', 'answerList' => array('A.是', ' B.否')), array('title' => '日常平均体温在36.3℃以上。', 'answerList' => array('A.是', ' B.否')), array('title' => '坐姿不固定，身体爱摇来摇去。', 'answerList' => array('A.是', ' B.否')), array('title' => '骨架偏小，外表看起来比实际体重要瘦。', 'answerList' => array('A.是', ' B.否')), array('title' => '小腿肌肉比较松，很容易被捏起来。', 'answerList' => array('A.是', ' B.否'))),
                array(array('title' => '你觉得自己的体重数字 ', 'answerList' => array('A.并不比生活中其他事情重要 ', 'B.比某些事情重要一些 ', 'C.比生活中大多数事情都重要得多 ', 'D.很重要，自己很在意')), array('title' => '你对当下发生的事情 ', 'answerList' => array('A.总是有活在当下的掌控感 ', 'B.能说出自己当下的感受和行为 ', 'C.不太关注它 ', 'D.几乎没有觉察，总容易失控和冲动')), array('title' => '和一群同事吃饭的时候，你通常', 'answerList' => array('A.高谈阔论，甚至不会注意到有哪些食物 ', 'B.与周围的人说说话，随意吃些东西 ', 'C.认真品尝食物的同时，与身边的人聊聊天 ', 'D.埋头一直吃不说话，或者刻意让自己吃得非常少')), array('title' => '你对甜食 ', 'answerList' => array('A.一点都不喜欢，讨厌吃甜的 ', 'B.不太喜欢，但吃一点还是可以的 ', 'C.比较喜欢，偏爱较甜的食物 ', 'D.超级热爱甜食，走到甜食店旁总忍不住要进去看看')), array('title' => '当你一个人吃东西时，你 ', 'answerList' => array('A.意识到自己在吃某样食物，并打算好要吃多少 ', 'B.能感觉到自己越来越饱了 ', 'C.看到眼前的食物越来越少了 ', 'D.什么都不想，就是吃')), array('title' => '你觉得自己的生活 ', 'answerList' => array('A.悠闲、轻松，完全由自己来支配 ', 'B.有一定压力，但知道如何来分配自己的时间与精力 ', 'C.有较大压力，常有身不由己的感觉 ', 'D.很有压力，生活把自己压得喘不过气来')), array('title' => '在你眼中，自己 ', 'answerList' => array('A.很优秀，很棒 ', 'B.还好，大多数人会喜欢自己 ', 'C.不太好，自己没什么大不了的 ', 'D.很糟糕，别人总瞧不起自己')), array('title' => '在你需要帮助的时候，你可以想到几个人？ ', 'answerList' => array('A.7人以上 ', 'B.3-7人 ', 'C.1-2人 ', 'D.除了自己，几乎没有其他人')), array('title' => '周末或节假日的时候，你喜欢 ', 'answerList' => array('A.参加盛大聚会 ', 'B.与几个要好的朋友聚会 ', 'C.和父母呆一起 ', 'D.一个人呆在房间里')), array('title' => '当你看到食物这个词时，你首先联想到的词是 ', 'answerList' => array('A.吃 ', 'B.开心 ', 'C.人情 ', 'D.爱'))),
                array(array('title' => '肌肤粗糙，经常为皮肤烦恼', 'answerList' => array('A.是', 'B.否')), array('title' => '面色很差', 'answerList' => array('A.是', 'B.否')), array('title' => '看上去比实际年龄老很多', 'answerList' => array('A.是', 'B.否')), array('title' => '有便秘烦恼', 'answerList' => array('A.是', 'B.否')), array('title' => '容易疲倦', 'answerList' => array('A.是', 'B.否')), array('title' => '经常肩痛、腰痛、痛经', 'answerList' => array('A.是', 'B.否')), array('title' => '上5楼会气喘', 'answerList' => array('A.是', 'B.否')), array('title' => '怕冷', 'answerList' => array('A.是', 'B.否')), array('title' => '喜欢喝冷饮、吃冷餐', 'answerList' => array('A.是', 'B.否')), array('title' => '酷爱甜点', 'answerList' => array('A.是', 'B.否')), array('title' => '不太喜欢蔬菜、水果', 'answerList' => array('A.是', 'B.否')), array('title' => '每餐必有鱼或肉', 'answerList' => array('A.是', 'B.否')), array('title' => '经常喝酒', 'answerList' => array('A.是', 'B.否')), array('title' => '到超市必采购方便食品或膨化食物', 'answerList' => array('A.是', 'B.否')), array('title' => '熬夜', 'answerList' => array('A.是', 'B.否')), array('title' => '睡眠时间不足6小时(包括6小时)', 'answerList' => array('A.是', 'B.否')), array('title' => '感到压力', 'answerList' => array('A.是', 'B.否')), array('title' => '吸烟', 'answerList' => array('A.是', 'B.否')), array('title' => '喝水不多', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '你对洋快餐的热衷程度?', 'answerList' => array('A、每周3次或更多。', 'B、每周2次以下。', 'C、基本不去。')), array('title' => '总是难以抗拒可口的甜点诱惑?', 'answerList' => array('A、每周有4份或以上的蛋糕作为茶点。', 'B、每周最多只有3次机会品尝茶点。', 'C、几乎从不吃这些甜腻的食品。')), array('title' => '你对菠菜、水果的“感情”如何?', 'answerList' => array('A、每周保持3天或以上的时间吃蔬菜，以沙拉为主。', 'B、每周3天或以上的时间吃蔬菜，以罐头为主。', '　C、每周只有一两天吃蔬菜，也很少饮用果汁。')), array('title' => '是否经常在外面就餐?', 'answerList' => array('A、几乎每天都有。', 'B、每周两次左右。', 'C、很少有应酬。')), array('title' => '是否嗜好含酒精饮料。尤其是伏特加、WHISKY?', 'answerList' => array('　A、经常这样。', '　B、偶尔喝一点。', '　C、从不喝酒。')), array('title' => '看看你餐桌上的肉类。', 'answerList' => array('A、餐餐见肉，而且以猪肉为主。', 'B、天天看到肉，但种类多样。', 'C、很少吃肉。')), array('title' => '怎样补充水分?', 'answerList' => array('A、渴了喝甜饮料。', 'B、经常喝矿泉水和纯净水。', 'C、以水、绿茶或不加牛奶和糖的红茶为主要饮料。')), array('title' => '总有在看电视的时候吃零食的习惯。', 'answerList' => array('A、每天如此。', 'B、每周3次左右。', 'C、很少。')), array('title' => '除了上下班.没有什么其他的运动方式。', 'answerList' => array('A、基本如此。', 'B、会找时间去健身房锻炼。', 'C、经常步行或骑车。')), array('title' => '健身方式的选择。', 'answerList' => array('A、以柔和的方式为主，如瑜珈、太极等', 'B、以中等强度的为主，如高尔夫、慢跑、骑车等。', '　C、以中等以上强度为主，如拳击、篮球、足球等。')), array('title' => '休闲方式。', 'answerList' => array('A、经常到郊外野炊。', 'B、很少去。', 'C、从不去。')), array('title' => '你家号称胖子家庭，全都胃口倍儿好。吃饭嘛嘛香。', 'answerList' => array('　A、基本上这样。', 'B、父母的身材比较胖，但兄弟姐妹的身材还算好。', 'C、父母的身材在同年龄的人当中，算得上苗条型。')), array('title' => '经常减肥。也经常反弹。', 'answerList' => array('A、是。', 'B、反弹，但概率不是很高。', 'C、基本不反弹。')), array('title' => '经常选择服用减肥药来减肥。', 'answerList' => array('A、是。', '　B、偶尔。', 'C、合理饮食加适度运动。')), array('title' => '你已经是个妈妈了。.', 'answerList' => array('A、坐月子期间，毫无顾忌地吃。', 'B、选择营养成分丰富的食物。', 'C、拒绝任何高热量食物。')), array('title' => '有何种不同的兴趣爱好。', 'answerList' => array('A、爱好比较丰富。', 'B、每月和朋友一起娱乐的机会不超过5次', 'C、每月和朋友们在一起的机会只有4次或以下。')), array('title' => '心情郁闷的时候。只想用吃东西来发泄不满和愤懑。', 'answerList' => array('A、经常如此。', 'B、偶尔这样。')), array('title' => '工作较为繁忙。', 'answerList' => array('A、非常繁忙。', 'B、很少加班。', 'C、几乎每个工作日都可以准时下班。')), array('title' => '性格开朗、幽默?', 'answerList' => array('A、很开朗，是朋友和同事中出了名的开心果。', 'B、你和大多数朋友一样，没有特别的个性，但是也没有明显的抑郁。', 'C、“郁闷”是你的口头禅。'))),
                // 该条测试题目过多
                array(array('title' => '你是不是经常一边吃零食一边做事？', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '买食物时，只买对胃口，不管它是否具有营养价值？　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '喜欢多油、味重的食物和奶油制品。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '经常到外边和朋友一起聚餐。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '经常不吃早餐，并且食无定时。进食速度很快。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '节食时，喜欢走极端，严格控制饮食。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '晚餐通常是最丰盛的。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '常常为自己找“吃”的借口。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '常常为缓解焦急不安的心情而暴饮暴食。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '能乘电梯就绝不爬楼梯。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '从不愿参加任何体育活动，并且对其毫无兴趣。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '没事时，喜欢躺着而不愿坐着。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '厌恶家务劳动。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '不管是父亲还是母亲身上，都能发现你胖的身影。', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '个性虽然开朗活泼，但却不喜欢运动。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '即使感到很热的时候，流汗也很少。', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '体质属于寒凉型。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '患有荷尔蒙分泌失调或神经失调。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '喜欢咖啡、红茶或罐装饮料。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '洗澡速度快，而且用的水偏热。', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '喜欢坐在电脑边整资料或玩游戏？　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '你平日特别偏爱冰冷食物，如冰淇淋等。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '喜欢熬夜，每天睡眠时间不到7小时。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '体重虽然没变，但体型已改变。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '属于那种穿上衣服才看起来瘦一些的体型。', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '减过好几次肥，减肥之后体重又反弹。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '即使不吃什么也会胖。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '常常午睡和不自觉地打盹。　　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '节假日不出门而闲在家里。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '身体容易疲倦。', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '腰围和臀围一样粗。', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '无聊时或心情不佳时，以吃东西来发泄。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '肚子虽然很饱，但是如果不吃会觉得不舒服、不安心。　', 'answerList' => array('A是', 'B不是', 'C偶尔')), array('title' => '即使吃饱了，但看到喜欢的东西，还是会继续去吃。　', 'answerList' => array('A是', 'B不是', 'C偶尔'))),
                array(array('title' => '最近你的体重好像增加了一点，你决定减肥。你目标是一个月减掉3公斤。你会用以下四种方法中的哪种？ ', 'answerList' => array('A.在节食的基础上进行比较剧烈的运动 ', 'B.苹果减肥法或主食减肥法，类似这些单吃一种食物的方法 ', 'C.早饭和午饭爱吃多少就吃多少，但是完全不吃晚饭 ', 'D.考虑营养平衡，在认真吃好三餐的基础上进行运动减'))),
                array(array('title' => '半夜突然觉得肚子好饿，你会怎么解馋？', 'answerList' => array('A、找朋友出去吃', 'B、找碗泡面吃', 'C、找点零食吃', 'D、睡觉或喝水'))),
                array(array('title' => '常常会抱怨老天太不公平：世界上为什么有那么多窈窕美女，而我偏偏不是其中的一员？', 'answerList' => array('A·YES', 'B·NO')), array('title' => '办公室里最让我烦的就是那个家伙，她每次都比我吃的多很多，可身材却比我瘦很多。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '我讨厌镜子里的自己。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '我天天都在想，今天又吃得太多了。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '天呀，我的大腿粗壮得像树干。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '当我在别人面前吃那些使人发胖的食品时，会让我觉得丢人，良心难安。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '我不喜欢别人从背后盯着我看，那样会让我担心：他在看什么呢，是不是已经注意到我的臀部线条太松！', 'answerList' => array('A·YES', 'B·NO')), array('title' => '我都快半年没游泳了，因为穿着游泳衣的我胖得像只小鸭子，这让我觉得难堪。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '如果我一天没有做做运动或者进行其它的体育锻炼，我就会感觉很差。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '天呀，我现在总是注意那些苗条美丽的女郎，我是不是个同性恋？', 'answerList' => array('A·YES', 'B·NO')), array('title' => '有不少食品，比如薯片、巧克力，每次吃它们我都会有一种强烈的罪恶感。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '我现在面临的最大困扰就是我的体形。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '每次我吃了过多的东西，或者热量高的食品，都会马上想到怎么把这些吃进去的卡路里用工作或者锻炼折腾掉。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '我害怕浴室里的镜子，因为自己的裸体实在让人倒胃口。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '吃了太多东西后，我有时会呕吐，或者吃泻药。', 'answerList' => array('A·YES', 'B·NO')), array('title' => '每天几乎都是这样开始的，刚刚起床我就默念：天灵灵，地灵灵，今天一定要少吃点。', 'answerList' => array('A·YES', 'B·NO'))),
                array(array('title' => '常常容易有口干舌燥的感觉。', 'answerList' => array('A.是', 'B.否')), array('title' => '尿液少而且颜色偏黄。', 'answerList' => array('A.是', 'B.否')), array('title' => '经常有便秘的现象，粪便又干又硬。', 'answerList' => array('A.是', 'B.否')), array('title' => '非常怕热，身体的温度偏高。', 'answerList' => array('A.是', 'B.否')), array('title' => '身体常有水肿的现象。', 'answerList' => array('A.是', 'B.否')), array('title' => '喜欢喝冷饮。', 'answerList' => array('A.是', 'B.否')), array('title' => '脸色发红，或是常常容易面红耳赤。', 'answerList' => array('A.是', 'B.否')), array('title' => '肌肉结实肥厚。', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '皮肤没有弹性、暗淡无光泽。', 'answerList' => array('A.是', 'B.否')), array('title' => '脸上容易长痘或粉刺。 ', 'answerList' => array('A.是', 'B.否')), array('title' => '容易疲劳，嗜睡，稍做运动就觉得累。 ', 'answerList' => array('A.是', 'B.否')), array('title' => '情绪不稳定，容易发怒。 ', 'answerList' => array('A.是', 'B.否')), array('title' => '牙龈经常出血，外伤口愈合慢、容易淤青。  ', 'answerList' => array('A.是', 'B.否')), array('title' => '感冒频繁；胃肠、肝、肾功能不好。', 'answerList' => array('A.是', 'B.否')), array('title' => '常出现便秘现象。 ', 'answerList' => array('A.是', 'B.否')), array('title' => '爱吃甜食，口中常有异味。 ', 'answerList' => array('A.是', 'B.否')), array('title' => '汗脚，四肢容易冰冷。', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '你常喝哪种饮料?   ', 'answerList' => array('A.可乐或其他碳酸饮料   ', 'B.纯净水   ', 'B.纯净水   ')), array('title' => '你的睡眠习惯是怎么样?   ', 'answerList' => array('A.常熬夜,早上很晚起    ', 'B.随心所欲,想睡就睡,想起就起', 'C.很规律,每天11点前睡   ')), array('title' => '以下三种放桌上你选哪个?   ', 'answerList' => array(' A.乳酪   ', 'B.牛排   ', 'C.海虾   ')), array('title' => '你口腔最大问题是以下那种?   ', 'answerList' => array(' A.口气大,有时会牙龈出血   ', 'B.有蛀牙,偶尔牙疼   ', 'C.现在很好保健最重要   ')), array('title' => '夏天,你的皮肤状况怎样?   ', 'answerList' => array(' A.经常过敏,特招蚊子   ', 'B.不是过油,就是过干,偶尔有粉刺   ', 'C.中性皮肤,要随时防晒  '))),
            ),
            /*
            * 美容测试
            * */
            array(
                // 该条评测结果陈述太多
                array(array('title' => '皮肤无光泽，用手触摸时较粗糙。', 'answerList' => array('A．是', 'B.否')), array('title' => '脸部毛孔越来越粗，尤以鼻部为甚。', 'answerList' => array('A．是', 'B.否')), array('title' => '眼尾及嘴角出现细小皱纹，笑时更加明显。', 'answerList' => array('A．是', 'B.否')), array('title' => '眼下浮肿形成眼袋。', 'answerList' => array('A．是', 'B.否')), array('title' => '脸上出现黑斑或原来的雀斑加深增多。', 'answerList' => array('A．是', 'B.否')), array('title' => '肌肉松弛、颧骨增高、嘴角似乎有些下垂。', 'answerList' => array('A．是', 'B.否')), array('title' => '出现双下巴。', 'answerList' => array('A．是', 'B.否')), array('title' => '颈部出现皱纹。', 'answerList' => array('A．是', 'B.否')), array('title' => '脸色暗淡、发黄，休息后不易恢复。', 'answerList' => array('A．是', 'B.否')), array('title' => '黑眼圈出现，熬夜后尤其明显。', 'answerList' => array('A．是', 'B.否')), array('title' => '肌肤脆弱，遇冷热刺激出现发红、疼痛甚至脱屑。', 'answerList' => array('A．是', 'B.否')), array('title' => '每次洗完脸，皮肤有紧绷感，一定要擦乳液或霜剂才舒服。', 'answerList' => array('A．是', 'B.否')), array('title' => '洗完脸拍上化妆水，水分立即被吸干或只揉乳液仍不够滋润。', 'answerList' => array('A．是', 'B.否')), array('title' => '平时无保养习惯，亦不做特殊护理。', 'answerList' => array('A．是', 'B.否')), array('title' => '经常蒸脸。', 'answerList' => array('A．是', 'B.否')), array('title' => '不易上妆，涂彩底后，粉与肌肤不易融合，易脱妆。', 'answerList' => array('A．是', 'B.否'))),
                array(array('title' => '你的皮肤外观如何？', 'answerList' => array('A、毛孔细致但缺乏光泽', 'B、比较细腻，但鼻头稍有油光及黑头的出现', 'C、毛孔粗大、有黑头，泛油光')), array('title' => '你的皮肤触感如何？', 'answerList' => array('A、全脸触感细腻，柔软', 'B、两颊触感光滑细腻，鼻头稍油腻', 'C、全脸触感油腻')), array('title' => '你化彩妆后通常会？', 'answerList' => array('A、皮肤有浮粉现象，妆面不服帖', 'B、皮肤吸粉较好，T区比较容积脱妆', 'C、皮肤吸粉速度快，容易脱妆')), array('title' => '你的皮肤容易产生粉刺吗？', 'answerList' => array('A、不，从来没有', 'B、是的，有时候', 'C、是的，经常发生')), array('title' => '你洗完脸皮肤通常会', 'answerList' => array('A、很快产生紧绷感', 'B、稍微有紧绷感', 'C、不会紧绷感')), array('title' => '你的脸部会出现起皮现象吗？', 'answerList' => array('A、经常出现', 'B、天气特别干时两颊有时会出现', 'C、从不')), array('title' => '你的皮肤现状如何？', 'answerList' => array('A、相当紧致，有弹性', 'B、有一点松弛', 'C、非常松弛')), array('title' => '你的脸部皱纹情况？', 'answerList' => array('A、基本上没有，眼角稍有幼纹', 'B、眼角有细纹', 'C、额头有细纹出现，眼角，嘴角皱纹较明显')), array('title' => '你的面霜通常给你什么感觉？', 'answerList' => array('A、不够滋润，有时还是觉得干燥', 'B、还好，没什么特别的感觉', 'C、不太愿意涂，喜欢清爽一些的感觉')), array('title' => '你觉得你的皮肤应该如何改善？', 'answerList' => array('A、保湿，因为比较干燥', 'B、两颊保湿，T区最好能去去油光、黑头', 'C、清爽，因为太油了'))),
                array(array('title' => '由于工作关系，一整天都必须保持相同的姿势，但因为懒惰，并不喜欢利用闲暇时间做些小体操。', 'answerList' => array('A．是', 'B.不是')), array('title' => '每天一定要喝咖啡、红茶，或其他刺激性的饮料。', 'answerList' => array('A．是', 'B.不是')), array('title' => '喜欢吃汉堡、薯条和可乐。', 'answerList' => array('A．是', 'B.不是')), array('title' => '每天睡眠时间不超过六小时。', 'answerList' => array('A．是', 'B.不是')), array('title' => '每天可以抽掉半包香烟。', 'answerList' => array('A．是', 'B.不是')), array('title' => '有时因为回家太晚，懒得御妆，不洗脸就睡着了。', 'answerList' => array('A．是', 'B.不是')), array('title' => '从来就不介意晒太阳，所以也不做防晒工作，就是夏天也不例外。', 'answerList' => array('A．是', 'B.不是')), array('title' => '其实，在两年前眼睛周围就已经出现小细纹了。', 'answerList' => array('A．是', 'B.不是')), array('title' => '脸部与身体的肤色有明显的差别，还是背部的皮肤摸起来比较细致。', 'answerList' => array('A．是', 'B.不是')), array('title' => '鼻部与两颊的毛孔越来越粗大。', 'answerList' => array('A．是', 'B.不是')), array('title' => '不管怎么遮盖，黑眼圈就是遮不掉。', 'answerList' => array('A．是', 'B.不是')), array('title' => '在日光灯下，肤色显得惨白没有血色。', 'answerList' => array('A．是', 'B.不是')), array('title' => '除了放假睡个大懒觉，否则没有任何办法解决浮肿的眼袋。', 'answerList' => array('A．是', 'B.不是')), array('title' => '肌肤既脆弱又容易过敏，对保养品不适应的频率越来越高了。', 'answerList' => array('', '', ''))),
                array(array('title' => '工作压力特别大，经常加班加点熬夜。', 'answerList' => array('A.是', 'B.否')), array('title' => '最近肤色加深了，不是健康的小麦肤色，而是黯黄褐色。', 'answerList' => array('A.是', 'B.否')), array('title' => '早起照镜子发现皮肤没有光泽，十分晦涩。', 'answerList' => array('A.是', 'B.否')), array('title' => '以前的同事都说你看起来憔悴了好多。', 'answerList' => array('A.是', 'B.否')), array('title' => '三餐不定时，多是外卖或快餐。', 'answerList' => array('A.是', 'B.否')), array('title' => '天气不那么热了，可脸上的出油情况反而加剧。', 'answerList' => array('A.是', 'B.否')), array('title' => '脸颊额头和下巴痘痘和粉刺层出不穷。', 'answerList' => array('A.是', 'B.否')), array('title' => '原有的斑点颜色变重。', 'answerList' => array('A.是', 'B.否')), array('title' => '肌肤干燥粗糙，摸上去手感很差劲。', 'answerList' => array('A.是', 'B.否')), array('title' => '皮肤抵抗力下降，很容易过敏。', 'answerList' => array('A.是', 'B.否')), array('title' => '眼角和嘴角的有幼纹。', 'answerList' => array('A.是', 'B.否')), array('title' => '黑眼圈和眼袋不请自来，尽管早晚使用眼霜。', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '皮肤含水量当然是多多益善。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '喝足够的水,皮肤就自然湿润。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '用热水洗脸,会加速皮肤水分的流失。', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '高保湿效果的保养品,能解决肌肤干燥的问题。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '保湿面膜是皮肤滋润的必备品。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '喷雾式的矿泉水或滑润液,可以在肌肤干燥时发挥功效。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '眼睛、嘴唇也是保湿的对象。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '手腕、手肘、膝盖、脚后踝,这些不外露的地方,可以不保湿。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '早晚勤擦眼霜,就能抵抗眼部干燥。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '眼部肌肤若是出现非常干燥的情况,就多涂上一些保养品加倍呵护。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '过敏的时候,什么都不要抹,干就只好干着,等过敏现象好点儿了再说。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '身体实在是太干燥了,在浴缸里好好泡上个把小时,让皮肤喝足水。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '给皮肤去角质,会加速皮肤的干燥起屑现象。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定')), array('title' => '护唇膏是随身必带之物。 ', 'answerList' => array('A.是', 'B.否', 'C.不一定'))),
                array(array('title' => '肤色暗淡，唇色、指甲颜色淡白。', 'answerList' => array('A.是', ' B.不是')), array('title' => '时常有头晕眼花的情况发生。', 'answerList' => array('A.是', ' B.不是')), array('title' => '最近一段时间经常心悸。', 'answerList' => array('A.是', ' B.不是')), array('title' => '睡眠质量不高，经常无缘无故失眠。', 'answerList' => array('A.是', ' B.不是')), array('title' => '经常会有手足发麻的情况发生。', 'answerList' => array('A.是', ' B.不是')), array('title' => '月经颜色比正常情况偏淡并且量少。', 'answerList' => array('A.是', ' B.不是'))),
                array(array('title' => '经常睡眠不足，生活作息不规律。', 'answerList' => array('A.是', 'B.否')), array('title' => '皮肤有时候会泛红、发肿。', 'answerList' => array('A.是', 'B.否')), array('title' => '曾经长过发痒的湿疹。', 'answerList' => array('A.是', 'B.否')), array('title' => '对特定物质会有过敏现象', 'answerList' => array('A.是', 'B.否')), array('title' => '有时候涂护肤品会有刺痛感。', 'answerList' => array('A.是', 'B.否')), array('title' => '在空气干燥的季节里，皮肤曾经干到脱皮。', 'answerList' => array('A.是', 'B.否')), array('title' => '属于混合性肌肤，鼻子周边会脱皮。', 'answerList' => array('A.是', 'B.否')), array('title' => '洗脸和泡澡后不涂护肤品，皮肤又干又紧绷。', 'answerList' => array('A.是', 'B.否')), array('title' => '经常睡眠不足，生活作息不规律。', 'answerList' => array('A.是', 'B.否')), array('title' => '喜欢吃快餐。', 'answerList' => array('A.是', 'B.否')), array('title' => '生活压力大。', 'answerList' => array('A.是', 'B.否')), array('title' => '常常一整天呆在空调房或者空气干燥的场所。', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '下面哪种射线对皮肤伤害严重? ', 'answerList' => array('A .UVA紫外线', 'B .UVB紫外线', 'C .伤害同样严重')), array('title' => '以下是最容易晒伤的场合,除了: ', 'answerList' => array('A .海边 ', 'B .游泳池 ', 'C .山坡', 'D .运动场 ')), array('title' => '在涂抹了防水型防晒霜后,在游泳或出汗时不需要再次使用。 ', 'answerList' => array('A .正确', 'B .错误 ')), array('title' => '如果防晒霜的SPF值为30,那么它提供的有效防晒时间比SPF值为15的产品长一倍。 ', 'answerList' => array('A .正确', 'B .错误 ')), array('title' => '如果年轻时皮肤被晒伤,会使成年以后患皮肤癌的几率加大。 ', 'answerList' => array('A .正确', 'B .错误 ')), array('title' => '如果被轻微晒伤,能够有所缓解的方法是: ', 'answerList' => array('A .在皮肤表面涂上薄薄一层凡士林油 ', 'B .洗个澡,然后在皮肤上涂上保湿乳或保湿液 ', 'C .什么也不做,等着晒伤的皮肤自己好转 ')), array('title' => '大部分防晒霜的保存期限是: ', 'answerList' => array('A .1年', 'B .3年', 'C .根据标签注明 ')), array('title' => '在强烈紫外线照射下,最好的保护措施是: ', 'answerList' => array('A .戴上遮阳帽,穿能遮住四肢的衣裤 ', 'B .呆在阴凉处', 'C .使用全效防晒霜 ', 'D .以上所有措施 ')), array('title' => '涂抹防晒霜的时间是: ', 'answerList' => array('A .出门前30分钟', 'B .出门前10分钟 ', 'C .马上就要出门时'))),
                array(array('title' => '你的皮肤非常干燥，你应该', 'answerList' => array('　　A. 涂上补湿霜，补充所需水分', '　　B. 立即喷补湿喷雾', '　　C. 涂一点带氧分的面霜，令皮肤产生多些水分')), array('title' => '游离基伤害你的皮肤时，你应该', 'answerList' => array('　　A. 涂一层厚厚的抗氧面霜，修补受损皮肤细胞', '　　B. 涂上维他命Ｃ面霜来回复皮肤的维他命', '　　C、什么是游离基？')), array('title' => '维他命Ａ酸的面霜又称“神奇面霜”，你希望它在什么部位发挥神奇作用呢？', 'answerList' => array('A. 暗疮', 'B. 缺水及敏感性皮肤', 'C. 暴露于阳光下的皮肤')), array('title' => '当你发现发尾开叉时，这表示', 'answerList' => array('A. 该修剪头发了', 'B. 是用专为干性头发而设的洗发水的时候了', 'C. 是将头发束成马尾的时候了')), array('title' => '购买头发造型产品时，应避免什么成分？', 'answerList' => array('A. 酒精', 'B. 香料', 'C. 止汗剂')), array('title' => '现在你拥有一把又短又厚又不贴服的头发，到发型屋时你会要求一个什么样的发', 'answerList' => array('A. 富层次感的发型', 'B. 发脚整齐的发型', 'C. 假发')), array('title' => '当你所穿的名贵丝衬被指甲钩出一个洞，你会', 'answerList' => array('A. 用指甲锉往同一方向锉平指甲', 'B. 尽快剪掉所有指甲', 'C. 剪短丝衬，并将它当成一对鱼网手套，下次戴着它穿丝衬')), array('title' => '指甲长出了倒刺，正在流血，你应该', 'answerList' => array('A. 用修甲棒轻轻将倒刺推回指甲旁', 'B. 涂一层厚厚的护手霜，软化倒刺', 'C. 用指甲钳剪掉倒刺')), array('title' => '若你需要穿上泳衣，你会在私密处做什么准备？', 'answerList' => array('A. 到美容院接受专业脱毛', 'B. 准备肥皂、水和剃刀，自已来一次脱毛行动', 'C. 彻底清除私密处的毛发')), array('title' => '你会用手袋内的钳子做什么？', 'answerList' => array('A. 在公司时，用钳子整理一下眉毛', 'B. 照倒后镜时，清除一下自已的汗毛', 'C. 在沙滩更衣室，拔掉私密处不听话的体毛'))),
                array(array('title' => '你的头发是以下哪种情况：', 'answerList' => array('A．头发稀疏', 'B．脱发', 'C．头发松软或干燥', 'D．头发缺乏光泽', 'E．头发太油', 'F．头发不生长', 'G．头发末端分叉', 'H．头皮屑过多'))),
                array(array('title' => '目前是否有湿疹，皮炎等肌肤问题？', 'answerList' => array('A.是', ' B.否')), array('title' => '肌肤是否曾患有湿疹，皮炎等症状？', 'answerList' => array('A.是', ' B.否')), array('title' => '肌肤是否表皮薄，毛细血管明显?', 'answerList' => array('A.是', ' B.否')), array('title' => '肌肤是否有固定的红血丝？', 'answerList' => array('A.是', ' B.否')), array('title' => '肌肤接触化妆品时，是否会有发痒，刺痛或灼烧感？', 'answerList' => array('A.是', ' B.否')), array('title' => '过去一两年中，是否曾因试用化妆品而导致肌肤炎症，出疹，过敏？', 'answerList' => array('A.是', ' B.否')), array('title' => '肌肤脆弱，遇到风吹，日晒，是否容易发痒，或有灼烧感或刺痛感？', 'answerList' => array('A.是', ' B.否')), array('title' => '温差变化较大时，肌肤是否容易产生不适反应？', 'answerList' => array('A.是', ' B.否'))),
                array(array('title' => '你的头发看上去', 'answerList' => array('A. 柔顺，有自然的光泽 ', 'B. 无光泽，发梢开叉较多 ', 'C. 毫无弹性，枯黄干燥 ')), array('title' => '你1 年内平均染烫几次', 'answerList' => array('A. 少于2 次 ', 'B. 2 ～ 5 次 ', 'C. 5 次以上 ')), array('title' => '造型方面，你往往', 'answerList' => array('A. 几乎很少用吹风机造型 ', 'B. 经常用吹风机造型 ', 'C. 每次洗完头都要用吹风机造型 ')), array('title' => '用食指和大拇指拉一根头发的两端，你发现', 'answerList' => array('A. 拉长后能尽快恢复到原来长度 ', 'B. 弹性不好，拉长后不容易恢复到原来长度 ', 'C. 缺乏弹性，容易断开'))),
            ),
            /*
             * 饮食测试
             * */
            array(
                array(array('title' => '您在餐后是否吃水果？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您在副食中吃绿叶或十字花科蔬菜，如菠菜、洋白菜、甘蓝、菜花或绿菜花吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '在副食中您吃莴苣、西红柿吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您在一天中是否喜欢将新鲜水果、干果和罐装水果作为零食？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您喜欢吃全麦面包或杂粮吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您喜欢吃黄红色的蔬菜，如胡萝卜或辣椒吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您常吃豆类食物，如大豆、豌豆或扁豆吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您常用洋葱、大蒜或草药来作为调味品并替代一部分食盐吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您吃深海中的鱼类，如金枪鱼、三文鱼与沙丁鱼吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您吃柑橘类水果，如柚子、橙子或橘子吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您将瓜子、花生或其它干果作为零食或放在午餐或晚餐中吃吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您吃割去肥肉的红肉或用大豆制品、豆类食物或豌豆作为补充铁的来源吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您吃低脂奶类食品，如低脂酸奶或低脂牛奶吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您在饭馆进餐时，也点蔬菜吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您在烹调时，用葵花子油、橄榄油或豆油替代猪油或牛油吗？', 'answerList' => array('A.经常吃', 'B.吃 ', 'C.很少吃或不吃')), array('title' => '您饮用水果汁或蔬菜汁吗？', 'answerList' => array('A.经常饮用', ' B.饮用', 'C.很少饮用或不饮用'))),
                array(array('title' => '你的身体向你发出了什么信号呢？', 'answerList' => array('A.头发干燥、变细、易断、脱发', 'B.夜晚视力降低', 'C.舌炎、舌裂、舌水肿', 'D.嘴角干裂', 'E.牙龈出血', 'F.味觉减退'))),
                array(array('title' => '吃饭不愿剩，经常吃完盘中所有食物。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '常吃咸菜以及咸鱼、腊肉等腌制品。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '经常吃方便面。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '经常吃刚屠宰的猪、牛、羊肉，认为其最新鲜，质量最好。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜爱吃动物内脏，如猪肝、猪大肠、羊杂碎等。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜欢选购白的馒头、挂面等面食，认为颜色越白越好。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜爱吃烧烤类食物，如羊肉串、烤鱿鱼等。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜欢在看电视、读书或行走时吃东西。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '不管食物营养价值如何，只要对胃口就买。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜欢吃素。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '为了某种目的，时长节食或严格限制饮食。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜欢用咖啡、冷饮或罐装甜饮料代替日常饮水。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '不喜欢吃全麦面或杂粮。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '长时间不喝牛奶或酸奶。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '在每3天的食谱中，都不会安排胡萝卜、西红柿。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '西瓜、草莓喜欢跳个大的买。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '用餐后马上吃水果。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '您的晚餐是否通常是三餐中最丰盛的？', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '不常吃大豆、豌豆或扁豆。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '不常吃洋葱、大蒜、姜。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '基本不吃河鱼或海鱼。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '不常吃柑橘类水果，如柚子、橙子或橘子。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '经常不吃早餐。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '从小到现在一直偏爱某类食物。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '菜里要是盐、味精放少了，会觉得没有味道很难下咽。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '炒菜时等油冒烟了才放菜。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '放了还几天的剩菜，只要您觉得没放环就加热后继续食用。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '每天刷碗时都用洗洁精。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '喜欢甜食，烹炒各种炒菜时都喜欢放些糖。', 'answerList' => array('A.偶尔', 'B.否', 'C.是')), array('title' => '常在农贸市场购买没有包装的豆腐和豆制品。', 'answerList' => array('A.偶尔', 'B.否', 'C.是'))),
                array(array('title' => '一种标明为93%无脂肪的食物意味着其中7%的热量来自脂肪。', 'answerList' => array('A.对', ' B.错')), array('title' => '“淡”橄揽油与普通橄榄油含有同样多的脂肪与热量。', 'answerList' => array('A.对', ' B.错')), array('title' => '深色面包比白面包含有更多食物纤维。', 'answerList' => array('A.对', ' B.错')), array('title' => '乡村式奶酪是一种优质的钙来源。', 'answerList' => array('A.对', ' B.错')), array('title' => '果仁在你试图控制体重时仍是很好的零食。', 'answerList' => array('A.对', ' B.错')), array('title' => '大量喝果汁是减轻体重的好办法。', 'answerList' => array('A.对', ' B.错')), array('title' => '罐头速冻蔬菜、水果常常比新鲜果菜更有营养。', 'answerList' => array('A.对', ' B.错')), array('title' => '豆奶能够完全代替牛奶。', 'answerList' => array('A.对', ' B.错')), array('title' => '大多数妇女应该服用含铁补剂。', 'answerList' => array('A.对', ' B.错')), array('title' => '患流感或感冒时吃奶制品能减轻病症。', 'answerList' => array('A.对', ' B.错'))),
                array(array('title' => '常常把肉和家禽上的脂肪去掉', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '食用水果时只清洁而不削去外皮', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '吃鸡肉时把皮去掉', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '为了让饭菜看起来更漂亮，常用饰菜来装饰一下', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '蔬菜只烹调到嫩脆即出锅', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '煮面条、米饭、其他谷物和蔬菜时所用的水中不放盐', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '烹调时使用的全是谷类', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '饮食中尽量包括不同颜色、不同口味的食品', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '将一些豆芙类食物放入沙拉、汤或其他食品中', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '为了增加钙含量,在沙拉和蔬菜上撒一些干酪', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '烹调时只用少量的水,而且一定要加上锅盖', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '用煮过蔬菜的水做汤或炖肉', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '烹调时一定会先尝尝味道,然后再加盐', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '常用烤、炒、蒸、炖等方法来降低脂防', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '吃含钙比较高的蔬菜,如青菜', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '常用果汁或其他调味品来代替盐', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '使用脂肪量较低的配料,如脱脂牛奶、瘦肉等', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '做汤或炖肉时放些奶粉以增加的摄入量', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '肉做好以后,把肥肉去掉', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不')), array('title' => '用水果、果酱来增加食品甜味', 'answerList' => array('A.总是', 'B.通常 ', ' C.有时', 'D.从不'))),
                array(array('title' => '常喝哪种牛奶?', 'answerList' => array('A.全脂牛奶', 'B.半脱脂牛奶', 'C.脱脂奶或豆奶')), array('title' => '多久吃一次红烧肉', 'answerList' => array('A.每天一次或多次', 'B.每周数次', 'C.偶尔或从不')), array('title' => '爱吃哪种甜点?', 'answerList' => array('A.高脂肪奶油苹果馅饼', 'B.水果沙拉和冰激凌', 'C.新鲜水果')), array('title' => '多久吃一次油炸食物?', 'answerList' => array('A.经常吃', 'B.每周1-2次', 'C.偶尔或从来不吃')), array('title' => '在餐馆里最爱点什么菜?', 'answerList' => array('A.牛、羊、猪肉', 'B.鸡或鱼', 'C.蔬菜')), array('title' => '喜欢用下列哪一组馅料夹三明', 'answerList' => array('A.奶油奶酪、花生酱、香肠、蛋黄酱', 'B.鸡肉、金枪鱼、鲑鱼', 'C.沙拉、农家奶酯、酸奶')), array('title' => '日常生活中,早餐经常吃下列哪一类食物?', 'answerList' => array('A.煎蛋或熏猪肉', 'B.涂黄油或人造黄油的烤面包', 'C.谷类食物和水果')), array('title' => '怎样烹调猪肉、排骨、香肠和其他富含脂肪的肉类?', 'answerList' => array('A.煎', 'B.烤', 'C.不吃肥肉')), array('title' => '喜欢怎样烹调蔬菜?', 'answerList' => array('A.炒菜,吃时加黄油或浇上奶酪浓酱汁', 'B.微波炉烹调、水煮,加少许油调味', 'C.微波炉烹调、水煮或蒸,不加调料'))),
                array(array('title' => '在用调料时,经常会刻意注意少放盐吗?', 'answerList' => array('A.少用或用含钠量低的盐', 'B.从未想这么多')), array('title' => '如果吃了含钠较多的食品,下一次就要吃含钠少的食品,这样可以保持盐摄入平衡吗?', 'answerList' => array('A.可以', 'B.不行')), array('title' => '经常把盐瓶放在哪里?', 'answerList' => array('A.柜子里边', 'B.厨房柜上或餐桌上,以便随手取到')), array('title' => '常用果汁,香料或其他草本植物给食品调味吗?', 'answerList' => array('A.是的', 'B.不是')), array('title' => '做面食和烫菜用的水中放盐吗？', 'answerList' => array('A.放盐', 'B.不放盐')), array('title' => '在超市选购食品时,常常看营养标签检查钠的含量吗?', 'answerList' => array('A.不看', 'B.当然要看')), array('title' => '在外边吃饭时,可瞩厨师在食品中少放盐吗?', 'answerList' => array('A.是的', 'B.不是')), array('title' => '对于加工的肉类如烤肉、火腿、香肠等，食用的量多吗？', 'answerList' => array('A.适量', 'B.用的比较多')), array('title' => '购买的食品或零食含钠多吗？', 'answerList' => array('A.含钠量较低', 'B.哪管那么多，好吃就行')), array('title' => '烹饪时总是尝过味道后发现菜淡了再撒点盐在上面？', 'answerList' => array('A.是', 'B.否')), array('title' => '爱吃多种蔬菜和水果吗？', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '天然维生素要比合成维生素好', 'answerList' => array('A.是 ', 'B.否')), array('title' => '维生素与无机盐补充剂可以使人更强壮,更有活力', 'answerList' => array('A.是 ', 'B.否')), array('title' => '经常出现头昏眼花、恶心呕吐、记忆力差、伤口经久不愈,是缺乏维生素B6', 'answerList' => array('A.是 ', 'B.否')), array('title' => '如果经常流鼻血,牙龈出血,舌尖干燥,容易感冒,是缺乏维生素C', 'answerList' => array('A.是 ', 'B.否')), array('title' => '缺乏维生素E会导致夜盲症,出现怕光、易流眼泪、毛发脱落等症状', 'answerList' => array('A.是 ', 'B.否')), array('title' => '缺乏维生素B2的症状是口角发炎、阴囊发炎、口腔溃疡、头皮屑多、手脚发热', 'answerList' => array('A.是 ', 'B.否')), array('title' => '如果有贫血、食欲不振、记忆力差、头昏、精神难以集中等表现,是缺乏维生素B12', 'answerList' => array('A.是 ', 'B.否')), array('title' => '足够的维生素可以代替正餐', 'answerList' => array('A.是 ', 'B.否')), array('title' => '饮食平衡就不需要特意补充维生素和无机盐了', 'answerList' => array('A.是 ', 'B.否')), array('title' => '粗粮中含的维生素及无机盐比较丰富', 'answerList' => array('A.是 ', 'B.否')), array('title' => '服用阿司匹林会损耗体内的维生素C', 'answerList' => array('A.是 ', 'B.否')), array('title' => '服用维生素A可促进视力', 'answerList' => array('A.是 ', 'B.否')), array('title' => '吸烟者需要额外补充维生素E和维生素C', 'answerList' => array('A.是 ', 'B.否')), array('title' => '服用维生素补充剂可以减肥', 'answerList' => array('A.是 ', 'B.否')), array('title' => 'B族维生素可以防止晕车、晕船', 'answerList' => array('A.是 ', 'B.否'))),
                array(array('title' => '有挑食、厌食、普遍食量减少的现象,孩子有不主动进食,甚至拒食的现象', 'answerList' => array('A.是', 'B.否')), array('title' => '免疫力低下,经常感冒发烧,并且极容易患各种感染性疾病', 'answerList' => array('A.是', 'B.否')), array('title' => '指甲出现白斑,手指长倒刺,出现地图舌(舌头表面有不规则的红白相间图形)', 'answerList' => array('A.是', 'B.否')), array('title' => '视力出现下降状况,容易导致夜视困难、近视、远视、散光等', 'answerList' => array('A.是', 'B.否')), array('title' => '出现外伤时,伤口不易愈合', 'answerList' => array('A.是', 'B.否')), array('title' => '易患皮炎、顽固性湿疹', 'answerList' => array('A.是', 'B.否')), array('title' => '青春期性发育迟缓,如男性生殖器睾丸与阴茎过小,睾酮含量低,性功能低下;女性乳腺发育及月经来潮晚;男女阴毛皆晚出现等', 'answerList' => array('A.是', 'B.否')), array('title' => '口腔溃疡反复发作', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '经常感到软弱无力、疲乏困倦', 'answerList' => array('A.是', 'B.否')), array('title' => '皮肤、黏膜、指甲、口唇等颜色总是苍白或苍黄色', 'answerList' => array('A.是', 'B.否')), array('title' => '头发干枯、易落', 'answerList' => array('A.是', 'B.否')), array('title' => '稍一运动就感到心悸、气短', 'answerList' => array('A.是', 'B.否')), array('title' => '经常有头晕、头痛、耳鸣、眼花、注意力不集中的症状', 'answerList' => array('A.是', 'B.否')), array('title' => '嗜睡,并且睡眠质量不好', 'answerList' => array('A.是', 'B.否')), array('title' => '总是觉得食欲减退、食不知味;儿童会出现厌食食,甚至异食症', 'answerList' => array('A.是', 'B.否')), array('title' => '对于生育期女性来说,经期时间少于3天,并且会有量少、色淡的现象', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '只要注意饮食花样,就可摄取足够的营养,对吗?', 'answerList' => array('A.正确', 'B.错误')), array('title' => '不吃肉、鱼等食物,人也可以保持身体健康吗?', 'answerList' => array('A.正确', 'B.错误')), array('title' => '吃零食对人体的健康有好处吗', 'answerList' => array('A.有', 'B.没有')), array('title' => '以下哪种食物中蛋白质的含量最高', 'answerList' => array('A.牛肉', 'B.鸡蛋', 'C.牛奶')), array('title' => '增加肌肉最好的办法是什么?', 'answerList' => array('A.多吃鸡蛋', 'B.多吃牛肉', 'C.多锻炼')), array('title' => '同样重量的蛋白质,脂肪、碳水化合物含的热量哪个多?', 'answerList' => array('A.一样多', 'B.蛋白质多', 'C.脂肪多')), array('title' => '食用哪种牛奶对正在学步的宝宝最好?', 'answerList' => array('A.全脂牛奶', 'B.低脂牛奶', 'C.无脂牛奶')), array('title' => '家庭烧的新鲜蔬菜肯定比罐头或冷冻蔬菜更有营养？', 'answerList' => array('A.正确', 'B.不正确')), array('title' => '多食高蛋白质和低糖食物是不是最理想的减肥措施?', 'answerList' => array('A.是', 'B.不是')), array('title' => '下列三者中哪种食物含热量最多？', 'answerList' => array('A.土豆', 'B.牛肉', 'C.面包')), array('title' => '进餐时,尽量不吃含淀粉的食物，如面包或土豆等,对吗?', 'answerList' => array('A.对', 'B.不对')), array('title' => '减肥的最好办法是什么?', 'answerList' => array('A.无脂肪饮食', 'B.高蛋白质饮食', 'C.多锻炼')), array('title' => '在饮食中,哪种脂肪是原发性心脏病的危险因素?', 'answerList' => array('A.饱和脂肪', 'B.不饱和脂肪', 'C.反式脂肪')), array('title' => '下列哪种食物含胆固醇最少?', 'answerList' => array('A.500克花生酱', 'B.500克瘦牛肉', 'C.500克羊肉')), array('title' => '维持人体生存所需要的盐每天摄入量应为多少？', 'answerList' => array('A.15克', 'B.5克', 'C.6~8克')), array('title' => '摄取过量的维生素不能使人更有劲吗？', 'answerList' => array('A.是', 'B.不是')), array('title' => '体重正常说明营养适中吗?', 'answerList' => array('A.是', 'B.不是')), array('title' => '作为饮食的补充,自然维生素比人造维生素好,对吗?', 'answerList' => array('A.对', 'B.不对')), array('title' => '低胆固醇和低脂肪饮食具有下列哪种作用？', 'answerList' => array('A.增加动脉壁脂质沉积', 'B.减少动脉壁脂质沉积', 'C.无关'))),
                array(array('title' => '在接触食品之前先用热的肥皂水洗手', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '抹布每隔几天就更换或消毒', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '微波炉中的溢出物立即清除', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '每次用完面板之后,都用洗洁精清洗', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '冰箱每周清洗一次,把放置时间长的食品及时扔掉', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '记录下冷冻食品的标记日期', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '在吃食物时从冰箱中拿出来现解冻', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '用不漏的容器存放鱼、肉等', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '加热剩菜时要冒出热气', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '做肉饼时要到中间没有红色', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '剩菜剩饭待放凉后再放入冰箱', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '食用密封食品时,先检查一下是否鼓起、泄漏', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '烧烤食品时,内外要均匀烧烤', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '煮熟的食品要用干净的盘子和叉子端到桌子上来', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '食品保温盒使用前要清洁', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '剩余的饭菜要在3~4天内吃完', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '在冷藏鸡时，要将内脏取出', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '烹饪肉和家禽时达到合理的温度', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '切肉、切蔬菜的刀和菜板要分开', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '将变质食物用塑料袋包好处理掉', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不')), array('title' => '不用菜勺来尝味', 'answerList' => array('A.总是', 'B.通常 ', 'C.有时 ', ' D.从不'))),
            ),
            /*
             * 症状测试
             * */
            array(
                array(array('title' => '您最近是否情绪压抑？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否过于较真？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否爱吃方便食品？如饼干、点心等。', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否偏爱肉食？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否缺少体育锻炼？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否每天吸烟支数乘以年龄数超过400?', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否爬楼梯时胸痛？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否手脚发凉、麻痹？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否经常明显地忘拿东西？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否血压高？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否血胆固醇或血糖值高？', 'answerList' => array('A.是', 'B.有一点', 'C.否')), array('title' => '您是否工作压力大？', 'answerList' => array('A.是', 'B.有一点', 'C.否'))),
                array(array('title' => '您是否觉得对什么事情都不感兴趣？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否总觉得身体有点问题，如头疼等？', 'answerList' => array('A.是', 'B.否')), array('title' => '你是否觉得身体很虚、没力气，总感到疲劳？', 'answerList' => array('A.是', 'B.否')), array('title' => '你是否觉得食欲不好，不想吃东西？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得不轻松，不舒服？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得心情不好？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得胸口闷闷的？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得自己很没用？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否常常想哭？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否比以前爱发脾气？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否睡眠质量很差？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否老是觉得很烦？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得记忆力不如以前？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得做事时常常无法集中注意力？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否总是想不开，甚至想到去死？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否总是把事情想得一团糟？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得想事情或做事情效率都比以前低？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否总是觉得没信心？', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '您是否心跳很快或很激烈？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否对很多事情不感兴趣？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否经常头痛？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否经常感到紧张或不安？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否抑郁？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否肌肉或关节疼痛？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否入睡困难？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否会莫名其妙地哭泣？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您的手或脚是否会麻木？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否容易兴奋、激动？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否会感觉胸闷，呼吸困难？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否会心悸？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否会头晕目眩？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '你是否会潮热？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否注意力难以集中？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '你是否会皮肤瘙痒？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '你是否会盗汗？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '你是否会感到疲乏或精力不济？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您脸上是否出现色斑，皮肤松弛？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有')), array('title' => '您是否对性缺乏兴趣？', 'answerList' => array('A.否', ' B.经常有', ' C.一直有'))),
                array(array('title' => '您是否没有一个可以亲密交谈的朋友？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否平时讨厌外出，常闷在家里？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否日常生活中没有属于自己的工作或感到在家庭中起不到什么作用？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否整天和衣躺着看电视？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否什么兴趣和爱好也没有？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否不关心时事，不读书也不看报？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否觉得活着没什么意义？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否平时爱发牢骚或埋怨？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否将“想死”作为口头禅？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否被人说成神经过敏，过分认真？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否经常会过分忧虑？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否经常身体懒得动，无精打采?', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否讨厌说或听笑话？', 'answerList' => array('A.是', 'B.否')), array('title' => '你是否有高血压或低血压？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否经常焦虑，易发脾气？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否对任何事都不会激动，无动于衷？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否什么事若非亲自动手，便不放心？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否不听别人的意见，固执己见？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否沉默寡言？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否配偶去世已有5年以上？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否不轻易对人说“谢谢”？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否爱讲自己过去值得自豪的事？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否对新的事物缺乏兴趣？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否什么事都要以自己为中心，否则就会内心不平？', 'answerList' => array('A.是', 'B.否')), array('title' => '您是否对任何事都缺乏忍耐力？', 'answerList' => array('A.是', 'B.否'))),
                array(array('title' => '①您是否会感到全身乏力？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '②您是否难以入睡？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '③您是否没有食欲？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '④您是否会骨骼和关节疼痛？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '①您是否会有潮热？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '②您是否出汗过多？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '③您是否有心悸？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '①您是否健忘？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '②您是否注意力难以集中？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '③您是否会无缘无故地恐慌？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '④您是否易怒、烦躁？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '⑤您是否对以前喜欢做的事情失去兴趣？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '①您是否对性失去兴趣？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '②您是否对性感的东西无动于衷？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '③您是否不再有晨勃？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '④您是否性交不再成功？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有')), array('title' => '⑤您是否性交时不能勃起？', 'answerList' => array('A.一直如此', 'B.经常', 'C.有时', 'D.没有'))),
                array(array('title' => '我在压力之下表现最好。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我常归咎外在环境太匆忙或紧张，以致无法作深入的自我反省。（ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我常因周围的人或事动作太慢而不耐烦。我讨厌等待或排队。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我休息时会觉得不安。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我似乎永远在赶时间。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我常为了完成某项事情而拒人于千里之外。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我只要片刻没和办公室联系就觉得不安。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我在做一件事时常会想到另一件事。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我处理危机时表现最好。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '处理突发状况的兴奋感，似乎比慢工出细活更让我觉得有成就。（ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我常为了处理突发状况，牺牲和亲友共处时间。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '当我为了处理突发状况，必须取消约会或中途离开，我认为别人应该能谅解。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我觉得处理突发状况让一天的生活更有意义。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我常边工作边吃饭。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '我一直认为总有一天能做我真正想做的事情。 （ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常')), array('title' => '一天下来办公桌上“已办”文件如果堆得高高的，我会很有成就感。（ ）', 'answerList' => array('A从不 ', 'B有时候', 'C常常'))),
                array(array('title' => '身体疲倦，全身发冷吗？', 'answerList' => array('A.是的', 'B.不是')), array('title' => '手脚发冷吗？', 'answerList' => array('A.是的', 'B.不是', '')), array('title' => '手指是否呈白色或青紫色，并伴有疼痛吗？', 'answerList' => array('A.是的', 'B.不是')), array('title' => '腰部周围发冷吗？', 'answerList' => array('A.是的', 'B.不是')), array('title' => '你是女性吗？', 'answerList' => array('A.是的', 'B.不是'))),
                array(array('title' => '您是否出现血便？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您的分泌物是否有臭味？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否常常便秘？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否比起鱼类更喜欢肉类？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否怀疑有结肠息肉？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否未接受过结肠检查？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否每日便形异常？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否进餐不规律？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否烦恼、精神压力大？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢辛辣、酸甜食物？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您的直系亲属是否有患结肠息肉的人？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否没有细嚼慢咽的习惯？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否偶有下腹部闷痛？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否进凉食物后易腹泻？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否基本不吃蔬菜？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否腹胀？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您便潜血检查是否呈阳性？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否习惯吃夜宵？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否每天饮酒？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否属于结肠功能不佳？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
                array(array('title' => '您是否特别喜欢喝啤酒？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否体型肥胖？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不喜欢吃蔬菜？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢吃动物的内脏？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您的直系亲属中是否有痛风患者？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否对外界精神刺激敏感？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否有肾结石或尿路结石既往病史？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢吃鱼的肝等食物？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢吃烧烤？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢吃烤肉？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢吃鱼卵？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否比起鱼更喜欢肉类？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否会每周做几次激烈运动？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您的体格检查中是否发现尿酸增高？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不喜欢喝茶或喝水？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否患高血压？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否有糖尿病或者处于高血糖临界值？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否被医生诊断有动脉粥样硬化？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您的大拇指根部是否肿胀？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否是中老年男性？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
                array(array('title' => '你是否每周排便次数少于3次？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你排便时是否粪质干硬？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否有排便困难感？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否感觉腹中胀满？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你有痔疮吗？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否不喜欢吃含粗纤维丰富的蔬菜和水果？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否不喜欢吃油润滋阴食品和饮料？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否喜欢吃辛辣温燥的刺激性食物？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否很喜欢吃柿子？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否经常服用强泻剂或洗肠？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否精神抑郁或过分激动？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否睡眠不足？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否有很重的口气？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你脸上是否容易长痘痘？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否在孕期？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否感觉排便不尽？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否喜欢在上厕所的时候看报纸、玩手机等？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有')), array('title' => '你是否排便时间长但是量少？', 'answerList' => array('A.是', 'B.否', ' B.不确定或没有'))),
                array(array('title' => '您是否γ-GTP增高？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您在超声波检查时是否被诊断为脂肪肝？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否肝功能异常？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否疲劳不易恢复？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否对外界刺激敏感？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否经常饮酒？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否饮酒同时吃干酪或干果？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否吸烟？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您的化验是否提示患高脂血症？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否超过标准体重？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否不经常运动？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否皮肤容易感染且不易治愈？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否患糖尿病或者处于高血糖临界值？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否手掌发红？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否常睡眠不足？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否事务繁忙，长时间未体检？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是比起鱼类更喜欢吃肉类食物？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否喜欢口味重的食物？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否经常9点后进晚餐？', 'answerList' => array('A.是', 'B.不一定', 'C.否')), array('title' => '您是否经常吃夜宵？', 'answerList' => array('A.是', 'B.不一定', 'C.否'))),
                array(array('title' => '您是否患高血压？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否总胆固醇高于正常值？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否三酰甘油高？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否高密度脂蛋白胆固醇低于40mg/dL？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否低密度脂蛋白胆固醇值大于150mg/dL？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '患您是否糖尿病或者处于高血糖临界值？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否血尿酸值高？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否吃着治疗心脏病的药？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您既往是否有心绞痛、心肌梗病史？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否常有四肢末端寒凉？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您下肢是否出现静脉曲张、静脉瘤？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否常见颜面和下肢水肿？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否每日三餐时间不固定？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否不爱吃鱼类？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否吸烟？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否喜欢蛋糕类零食？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否不限制盐分摄取？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否不喜欢吃蔬菜？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否常有睡眠不足？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否')), array('title' => '您是否对外界刺激和压力比较敏感？', 'answerList' => array('A.是', 'B.不一定 ', ' C.否'))),
            )
        );

        $answer = $answers[$homeIndex][$answersType];
        try {
            MasterManager::setAnswerInfo($answer);
        } catch (Exception $e) {
            LogUtils::error("ActivityConstant::getAnswer2()  ---->>> exception: " . $e->getMessage());
        }
        return $answer;
    }

    /**
     * @param $homeIndex : 首页六大类之一id
     * @param $answersType : 题目列表之一id
     * @param $score : 题目列表之一id
     */
    public static function getAnswerTestResult($homeIndex, $answersType, $score)
    {   /* 数据结构：
         *          结果陈述：优、良、中、差；
         *          -->1.其题目当中有的是分数高的陈述差，反之
         *          -->2.其题目当中有的是个数来判断
         *          -->3.有的是多项判断
         *          -->4.有的是联合判断
         *          -->4.有的是单项规则判断
         *          -->……………………
         * ====但不管这些规则数据结构都是陈述好到差传递====
         * ====至于规则不同差异由逻辑判断来实现====
         * ====如果判断规则没有根据递进式评论陈述则由字母顺序获得陈述====
         * */

        $result = [
            // 健康测试
            [
                ['super' => "你的睡眠质量良好，但注意睡眠时间以8小时为宜，休息时间过长也是不好的。", 'good' => "", 'medium' => "你的睡眠质量较差，容易导致你做事效率降低，注意力容易不集中，需要有意识地进行调节。", 'bad' => "你存在严重的睡眠障碍，头晕，肌肉酸疼等，都是低质量睡眠造成的恶果。"],
                ['super' => "不错，您的自我保健常识很丰富。但要付诸实践。", 'good' => "您的自我保健常识较丰富，但有些问题有待加强认识。", 'medium' => "", 'bad' => "您的自我保健常识较为匮乏，建议您订购39魔方进行学习。"],
                ['super' => "表明你对运动有较好的认识，运动观也正确。", 'good' => "", 'medium' => "一般。", 'bad' => "你对运动观念较模糊，运动也较盲目，希望你加强这方面知识的学习。"],
                ['super' => "很好，你还没有产生心理疲劳;分数一般的开始注意工作和生活的平衡是一个明智的选择;", 'good' => "", 'medium' => "", 'bad' => "情况不妙，也许真的到了改变你工作环境和方向的时候了，这样或许可以避免心理疲劳程度的加重。但此时也要当心，毕竟心累可能已经对你产生了影晌，再加上你的判断力和信心可能已经失去了往日的客观，建议你话专业的职业顾问机构帮你进行分析评估，这不失为帮助自身职业发展的明智之举。"],
                ['super' => "适合你的焦虑心理消除法是一个人到安静的地方散散心。准点星座特别建议到山上或者海边等自然风光优美的地方，在大自然的怀抱中尽情享受，可以消除你身心的疲劳，得到最好的放松。", 'good' => "你可以通过运动或者健身来消除焦虑情绪。也许是一天充满惊喜与激情的约会，也许是和朋友约好去打打网球，总之，你需要动感的一天来驱散你的焦虑。尽情地释放、尽情地大笑，这是你克服焦虑的要领。", 'medium' => "对于你而言，目前身体上的紧张感比精神上的焦虑感更加严重。你是不是常常熬夜加班或者学习为手边的任务焦头烂额呢？准点星座建议这种情况下的你应该首先选择的是休息，哪怕只是在家里发呆也会减轻你当前的焦虑和疲惫哦。", 'bad' => "在你焦虑的时候，就约上朋友出去聚会吧！在众多朋友的环境里尽情宣泄，不管是和朋友倾诉，还是一起去KTV大声唱歌，都会在不知不觉中带走你的焦虑和烦闷。"],
                ['super' => "右脑型。恭喜你了，由于当今社会右脑型人已经越来越多，所以也更凸显出充满想象力，勇于尝试的右脑型人的可贵。", 'good' => "", 'medium' => "", 'bad' => "左脑型。很不幸，你算多数人中的一个，所以，现在开始训练使用右脑！"],
                ['super' => "好！", 'good' => "较好！", 'medium' => "疲劳！", 'bad' => "严重疲劳！"],
                ['super' => "　干得漂亮！看起来你所有的运动习惯都足以让运动伤痛敬而远之。保持下去，对于训练变化带来的、任何可能导致受伤的因素，都要保持警戒之心。", 'good' => "", 'medium' => "　现在你可能没有伤痛困扰，但是你还是可以做出改进来确保你的健康状况可以延续下去。将那些你得分项目的“降低风险”建议运用到日常跑步锻炼中。", 'bad' => "专家们认为，大多数过度运动造成的伤病，其成因都不会是单一的。多数情况下，至少有两种或三种因素综合在一起，导致你发生伤病的情况。为了防微杜渐，请仔细阅读那些你得分项目的“降低风险”贴士，并把它们运用到日常跑步锻炼中。"],
                ['super' => "你对于转基因食品的危险性有深刻的理解认识。首先从避免摄取转基因食品开始吧。", 'good' => "可以看出你对转基因食品有某种程度的认识。摄取含转基因的食品，只有持续数十年，或许更长时间，影响才会出现。", 'medium' => "你还不能认识转基因食品的隐患。我想有必要在重视生产性之前，进一步推进对人类健康的研究。认清遗传基因操作的危险性吧。", 'bad' => "你似乎对转基因食品一无所知。一不留心长期摄取的话，很可能引起无法挽回的问题。"],
                ['super' => "现在没有抑郁倾向，但如果持续无节制地生活的话，会引起身体的障碍，不久会诱发精神上的障碍，不久会诱发精神上的障碍。因此还是保持有规律的生活习惯吧。", 'good' => "即使是看不出抑郁症的直接影响，但想必已经感到慢性疲劳，别忘了接受全身的健康检查。首先，从有规律的饮食生活开始，缓解精神压力，需要做适度运动。    ", 'medium' => "开始出现影响身体及精神的抑郁状态。建议首先与上司或专业医生商谈。请从改善不良的生活习惯开始，一个人自我烦恼很危险。", 'bad' => "可以认为患抑郁症的危险信号已经出现。鼓起勇气，咨询一下心理医生或者精神科专家等。另外，多与家人交流极为重要。"],
                ['super' => "", 'good' => "肾功能异常尚不肯定，但是肾脏已超负荷。检查每日的尿量、尿颜色、味和浑浊程度是很重要的，不要错过注意信号。注意口味咸淡和肥胖。", 'medium' => "怀疑有肾脏疾病或有肾功能异常。不仅要做尿检、尿沉渣试验，血液检查（尿素氮、肌酐、尿酸），肾脏和输尿管的超声检查，腹部螺旋CT、肾盂输尿管造影检查也是必不可少的。", 'bad' => "已出现肾功能异常。将来可能出现肾病综合征或肾功能不全。应即刻就诊于专科医生，检查肾功能受损的原因和及时接受治疗。"],
                ['super' => "现阶段没有肾脏疾病，但建议每年做一次常规体检。规律的生活习惯、饮食平衡、适当的运动是很重要的。", 'good' => "", 'medium' => "", 'bad' => ""],
            ],
            [],
            [],
            [],
            [],
            [],
        ];
    }
}